-   branch: master
    event: pull
    release:
        build: alpha
        publish: false
        prerelease: true
        draft: false
    destinations: 
        group: alpha_group
        store:
            ios:
            android:
        mandatory_update: false
        notify_testers: true
